<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domain" nsURI="https://org.trs.domain" nsPrefix="org.trs.domain">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topicOfInterest" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Indoor" eSuperTypes="#//Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingHours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Outdoor" eSuperTypes="#//Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meansOfTransportation"
        eType="#//TransportationMode" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weatherCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserPreferences">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferredItinerary" eType="#//Itinerary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priceRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferredTransportationMode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferredPOI" eType="#//Scenario"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Gender" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Occupation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Itinerary"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TransportationMode" serializable="false">
    <eLiterals name="BIKE"/>
    <eLiterals name="CAR" value="1"/>
    <eLiterals name="WALK" value="2"/>
    <eLiterals name="PUBLIC" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TRSDomain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userPreference" upperBound="-1"
        eType="#//UserPreferences" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userProfile" eType="#//UserProfile"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" eType="#//Scenario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data"/>
</ecore:EPackage>
