<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RecommenderSystem" nsURI="https://org.rs" nsPrefix="org.rs">
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborativeFiltering" eSuperTypes="#//Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentBased" eSuperTypes="#//Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContextAware" eSuperTypes="#//Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeBased" eSuperTypes="#//Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="SocialBased" eSuperTypes="#//Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="DemographicBased" eSuperTypes="#//Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="HybridBased" eSuperTypes="#//Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="Other" eSuperTypes="#//Algorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPreProcessing"/>
  <eClassifiers xsi:type="ecore:EClass" name="NLP" eSuperTypes="#//DataPreProcessing"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureScalling" eSuperTypes="#//DataPreProcessing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vectorisation" eSuperTypes="#//DataPreProcessing"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuplicatesRemoval" eSuperTypes="#//DataPreProcessing"/>
  <eClassifiers xsi:type="ecore:EClass" name="MissingDataManipulation" eSuperTypes="#//DataPreProcessing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Normalisation" eSuperTypes="#//DataPreProcessing"/>
</ecore:EPackage>
